# Generated by Django 2.0.6 on 2020-09-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True)),
                ('post_code', models.CharField(blank=True, max_length=6, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_description', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('author_information', models.CharField(blank=True, max_length=200, null=True)),
                ('dangdang_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('editor', models.CharField(blank=True, max_length=80, null=True)),
                ('press', models.CharField(blank=True, max_length=40, null=True)),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
                ('book_image', models.CharField(blank=True, max_length=50, null=True)),
                ('sales', models.CharField(blank=True, max_length=20, null=True)),
                ('inventory', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comment', models.IntegerField(blank=True, null=True)),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=30, null=True)),
                ('print_time', models.DateTimeField(blank=True, null=True)),
                ('impression', models.IntegerField(blank=True, null=True)),
                ('sponsor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_number', models.CharField(blank=True, max_length=20, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TBook')),
            ],
            options={
                'db_table': 't_car',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TAddress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderItem',
            fields=[
                ('order_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TBook')),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TOrder')),
            ],
            options={
                'db_table': 't_order_item',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TUser'),
        ),
        migrations.AddField(
            model_name='tcar',
            name='id',
            field=models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TCategory'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.TUser'),
        ),
    ]
